package com.carparts.service;

import com.carparts.domain.AppUser;
import com.carparts.repository.AppUserRepository;
import com.carparts.repository.ReportingRepository;
import com.carparts.repository.ReportingRepository.UserIdentity;
import java.util.Optional;
import java.util.UUID;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** Proving who somebody is. */
@Service
public class AuthService {

    private final AppUserRepository users;
    private final ReportingRepository reporting;
    private final PasswordEncoder passwords;

    /**
     * A real digest of a value nobody knows, verified against when no account matches.
     *
     * <p>Without it, an unknown username returns in microseconds while a real one costs the
     * quarter-second BCrypt deliberately takes, and that difference is measurable over the
     * network: somebody with a list of usernames could sort the real from the invented without
     * ever guessing a password. Hashing regardless keeps both paths equally slow.
     *
     * <p><b>Generated by the encoder rather than written as a literal.</b> A hand-written digest
     * has to be a well-formed one or {@code matches} rejects it on sight and returns early —
     * which silently removes the delay this exists to create. A constant that looked valid did
     * in fact still cost the full time, but only because this implementation tolerates a salt
     * the reference one refuses; that is a security property resting on a parser's leniency, and
     * it would break on an upgrade with nothing failing. Encoding a random value here costs one
     * BCrypt at start-up and cannot drift.
     *
     * <p>The preimage is a fresh UUID that is never stored, so it is not a password anybody can
     * present even in principle.
     */
    private final String noSuchAccount;

    public AuthService(AppUserRepository users, ReportingRepository reporting,
                       PasswordEncoder passwords) {
        this.users = users;
        this.reporting = reporting;
        this.passwords = passwords;
        this.noSuchAccount = passwords.encode(UUID.randomUUID().toString());
    }

    /**
     * Checks a username and password, and returns who they turn out to be.
     *
     * <p><b>Every failure is the same failure.</b> No such username, wrong password, and a
     * disabled account all return empty, and the endpoint turns that into one 401 with one
     * message. Distinguishing them would turn the login form into a way of asking whether an
     * account exists — and "that user is disabled" tells somebody they have found a real one.
     *
     * <p>The identity comes from {@code v_user_identity} rather than from the entity, because
     * the token needs the department and the manager flag, and the view joins them in the row it
     * has already produced. Reading them off {@link AppUser} would walk two lazy associations
     * for facts one query already holds.
     */
    @Transactional(readOnly = true)
    public Optional<UserIdentity> login(String username, String password) {
        Optional<AppUser> account = users.findByUsername(username);

        // Verified even when there is no account, so the two paths take the same time.
        String digest = account.map(AppUser::getPasswordHash).orElse(noSuchAccount);
        boolean correct = passwords.matches(password, digest);

        if (account.isEmpty() || !correct || !account.get().isEnabled()) {
            return Optional.empty();
        }
        return reporting.findIdentityByUsername(username);
    }
}
